<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="XSD">
      <schema location="oramds:/apps/AIAMetaData/IIPComponents/CommonExchangeModelLibrary/Core/Common/V1/IIPHeader.xsd"/>
      <rootElement name="EBMHeader" namespace="ikea.com/system/iip/IIPHeader/1.0/"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="XSD">
      <schema location="oramds:/apps/AIAMetaData/IIPComponents/CommonExchangeModelLibrary/Core/Common/V1/IIPHeader.xsd"/>
      <rootElement name="IIPFaultMessage" namespace="ikea.com/system/iip/IIPFaultMessage/1.0/"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.6.0(build 111214.0600.1553) AT [TUE OCT 15 15:03:56 CEST 2013]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:corecomfault="ikea.com/system/iip/IIPFaultMessage/1.0/"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:wsa="http://schemas.xmlsoap.org/ws/2003/03/addressing"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:xacml="urn:oasis:names:tc:xacml:2.0:policy:schema:cd:04"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:corecomcust="ikea.com/system/iip/IIPHeader/1.0/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:xacml-context="urn:oasis:names:tc:xacml:2.0:context:schema:cd:04"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl corecomfault wsa xacml xsd corecomcust xacml-context bpws xp20 mhdr bpel oraext dvm hwf med ids bpm xdk xref ora socket ldap">
  <xsl:template match="/">
    <corecomfault:IIPFaultMessage>
		<corecomfault:MessageID>
			<xsl:value-of select="/corecomcust:EBMHeader/corecomcust:MessageID"/>
        </corecomfault:MessageID>
		<corecomfault:EBMName>
			<xsl:text disable-output-escaping="no"></xsl:text>
		</corecomfault:EBMName>
        <corecomfault:CEMName>
			<xsl:value-of select="/corecomcust:EBMHeader/corecomcust:CEMName"/>
        </corecomfault:CEMName>
        <corecomfault:OperationName>
			<xsl:value-of select="/corecomcust:EBMHeader/corecomcust:OperationName"/>
        </corecomfault:OperationName>
		<corecomfault:EnterpriseServiceName/>
		<corecomfault:ECID/>
        <corecomfault:EnvironmentID/>
      <corecomfault:ErrorContext>
        <corecomfault:ErrorCode/>
        <corecomfault:ErrorText/>
        <corecomfault:StackTrace/>
        <corecomfault:SeverityLevel/>
      </corecomfault:ErrorContext>
      <corecomfault:FaultingService>
        <corecomfault:FaultingServiceName/>
        <corecomfault:FaultingServiceImplementationType/>
        <corecomfault:FaultingServiceInstanceID/>
      </corecomfault:FaultingService>
      <corecomfault:MessageReference>
        <corecomfault:MessageID/>
        <corecomfault:ObjectReferenceID/>
      </corecomfault:MessageReference>
      <corecomfault:SenderMessageReference>
        <corecomfault:MessageID/>
        <corecomfault:ObjectReferenceID/>
      </corecomfault:SenderMessageReference>
      <corecomfault:TargetMessageReference>
        <corecomfault:MessageID/>
        <corecomfault:ObjectReferenceID/>
      </corecomfault:TargetMessageReference>
    </corecomfault:IIPFaultMessage>
  </xsl:template>
</xsl:stylesheet>
