<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:tns="http://ws.fwk.ikea.com/business-call" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:ns0="ikea.com/cem/OrderAndDelivery/DeliverySchedule/V0/" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:ns2="urn:oasis:names:tc:xacml:2.0:context:schema:cd:04"
                xmlns:ns4="http://schemas.xmlsoap.org/ws/2003/03/addressing"
                xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:ns1="ikea.com/system/iip/CreateDeliveryScheduleDESProvABCSService/1.0/"
                xmlns:svcdoc="http://xmlns.oracle.com/Services/Documentation/V1"
                xmlns:ns3="http://schemas.oracle.com/service/bpel/common"
                xmlns:corecom="ikea.com/system/iip/IIPHeader/1.0/"
                xmlns:ns5="urn:oasis:names:tc:xacml:2.0:policy:schema:cd:04"
                xmlns:ns6="ikea.com/system/iip/IIPFaultMessage/1.0/"
                xmlns:wsp="http://www.w3.org/2002/ws/policy/ns/ws-policy"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:fwk="http://ws.fwk.ikea.com/fwk-service-call"
                xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="oramds:/apps/AIAMetaData/IIPComponents/ApplicationConnectorServiceLibrary/DES/V1/ProviderABCS/CreateDeliveryScheduleDESProvABCS.wsdl"/>
            <oracle-xsl-mapper:rootElement name="CreateDeliveryScheduleEBM" namespace="ikea.com/cem/OrderAndDelivery/DeliverySchedule/V0/"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="oramds:/apps/AIAMetaData/IIPComponents/ApplicationObjectLibrary/DES/V1/wsdls/CreateDeliveryScheduleWSLookup.wsdl"/>
            <oracle-xsl-mapper:rootElement name="BsGetWSAddressRequest" namespace="http://ws.fwk.ikea.com/business-call"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.3.0(XSLT Build 170820.1700.2557) AT [FRI JUL 08 15:32:18 CEST 2022].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="MessageId"/>
   <xsl:param name="ClientID"/>
   <xsl:param name="EnvironmentID"/>
   <xsl:template match="/">
      <tns:BsGetWSAddressRequest>
         <tns:EBCHeader>
            <fwk:clientId>
               <xsl:value-of select="$ClientID"/>
            </fwk:clientId>
            <fwk:messageId>
               <xsl:value-of select="$MessageId"/>
            </fwk:messageId>
            <fwk:environmentId>
               <xsl:value-of select="$EnvironmentID"/>
            </fwk:environmentId>
            <fwk:originator>
               <xsl:text disable-output-escaping="no">IIP</xsl:text>
            </fwk:originator>
            <fwk:wsendpointProtocolVersion>
               <xsl:text disable-output-escaping="no">1.0</xsl:text>
            </fwk:wsendpointProtocolVersion>
            <fwk:ebccontractVersion>
               <xsl:text disable-output-escaping="no">1.8.1</xsl:text>
            </fwk:ebccontractVersion>
         </tns:EBCHeader>
         <tns:BsGetWSAddressRequestPayload>
            <tns:GetWsAddressRequest>
               <tns:LookupData>
                  <tns:UserId>
                     <xsl:text disable-output-escaping="no">s-oitp-u-global</xsl:text>
                  </tns:UserId>
                  <tns:EbcName>
                     <xsl:text disable-output-escaping="no">EBCDEPDS01</xsl:text>
                  </tns:EbcName>
               </tns:LookupData>
            </tns:GetWsAddressRequest>
         </tns:BsGetWSAddressRequestPayload>
      </tns:BsGetWSAddressRequest>
   </xsl:template>
</xsl:stylesheet>
