<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:ns0="http://ws.fwk.ikea.com/business-call" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:tns="ikea.com/cem/OrderAndDelivery/DeliverySchedule/V0/" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:sp="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702"
                xmlns:wsp="http://www.w3.org/ns/ws-policy" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:svcdoc="http://xmlns.oracle.com/Services/Documentation/V1"
                xmlns:ns5="urn:oasis:names:tc:xacml:2.0:policy:schema:cd:04"
                xmlns:ns2="urn:oasis:names:tc:xacml:2.0:context:schema:cd:04"
                xmlns:ns4="http://schemas.xmlsoap.org/ws/2003/03/addressing"
                xmlns:ns1="ikea.com/system/iip/CreateDeliveryScheduleDESProvABCSService/1.0/"
                xmlns:ns3="http://schemas.oracle.com/service/bpel/common"
                xmlns:corecom="ikea.com/system/iip/IIPHeader/1.0/" xmlns:ns6="ikea.com/system/iip/IIPFaultMessage/1.0/">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="oramds:/apps/AIAMetaData/IIPComponents/ApplicationObjectLibrary/DES/V1/wsdls/CreateDeliverySchedule.wsdl"/>
            <oracle-xsl-mapper:rootElement name="BsScheduleLocationsResponse" namespace="http://ws.fwk.ikea.com/business-call"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="oramds:/apps/AIAMetaData/IIPComponents/ApplicationConnectorServiceLibrary/DES/V1/ProviderABCS/CreateDeliveryScheduleDESProvABCS.wsdl"/>
            <oracle-xsl-mapper:rootElement name="CreateDeliveryScheduleResponseEBM" namespace="ikea.com/cem/OrderAndDelivery/DeliverySchedule/V0/"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.3.0(XSLT Build 170820.1700.2557) AT [FRI FEB 14 13:45:13 GMT+05:30 2020].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:CreateDeliveryScheduleResponseEBM>
         <tns:DataArea>
            <tns:CreateDeliveryScheduleResponse>
               <tns:DeliveryScheduleResponse>
                  <tns:DATA>
                     <tns:OutVoSchedulingResponse>
                        <tns:ShipmentId>
                           <tns:ShpNumber>
                              <xsl:value-of select="/ns0:BsScheduleLocationsResponse/ns0:OutVoSchedulingResponse/ns0:ShipmentId/ns0:ShpNumber"/>
                           </tns:ShpNumber>
                           <tns:Creator>
                              <tns:Code>
                                 <xsl:value-of select="/ns0:BsScheduleLocationsResponse/ns0:OutVoSchedulingResponse/ns0:ShipmentId/ns0:Creator/ns0:Code"/>
                              </tns:Code>
                              <tns:BuType>
                                 <xsl:value-of select="/ns0:BsScheduleLocationsResponse/ns0:OutVoSchedulingResponse/ns0:ShipmentId/ns0:Creator/ns0:BuType"/>
                              </tns:BuType>
                           </tns:Creator>
                        </tns:ShipmentId>
                        <tns:SchedulingResponseReport>
                           <tns:Text>
                              <xsl:value-of select="/ns0:BsScheduleLocationsResponse/ns0:OutVoSchedulingResponse/ns0:SchedulingResponseReport/ns0:Text"/>
                           </tns:Text>
                           <tns:SchedulingSuccessFlag>
                              <xsl:value-of select="/ns0:BsScheduleLocationsResponse/ns0:OutVoSchedulingResponse/ns0:SchedulingResponseReport/ns0:SchedulingSuccessFlag"/>
                           </tns:SchedulingSuccessFlag>
                           <tns:SchedulingLocationResultList>
                              <xsl:for-each select="/ns0:BsScheduleLocationsResponse/ns0:OutVoSchedulingResponse/ns0:SchedulingResponseReport/ns0:SchedulingLocationResultList/ns0:VoSchedLocationResult">
                                 <tns:VoSchedLocationResult>
                                    <tns:ObjectiveType>
                                       <xsl:value-of select="ns0:ObjectiveType"/>
                                    </tns:ObjectiveType>
                                    <tns:SchedulingReasonCode>
                                       <xsl:value-of select="ns0:SchedulingReasonCode"/>
                                    </tns:SchedulingReasonCode>
                                    <tns:BuAddress>
                                       <tns:Sequence>
                                          <xsl:value-of select="ns0:BuAddress/ns0:Sequence"/>
                                       </tns:Sequence>
                                       <tns:BusinessUnit>
                                          <tns:Code>
                                             <xsl:value-of select="ns0:BuAddress/ns0:BusinessUnit/ns0:Code"/>
                                          </tns:Code>
                                          <tns:BuType>
                                             <xsl:value-of select="ns0:BuAddress/ns0:BusinessUnit/ns0:BuType"/>
                                          </tns:BuType>
                                       </tns:BusinessUnit>
                                    </tns:BuAddress>
                                 </tns:VoSchedLocationResult>
                              </xsl:for-each>
                           </tns:SchedulingLocationResultList>
                        </tns:SchedulingResponseReport>
                        <tns:SchedulingResponseReservationList>
                           <xsl:for-each select="/ns0:BsScheduleLocationsResponse/ns0:OutVoSchedulingResponse/ns0:SchedulingResponseReservationList/ns0:VoSchedRespReservation">
                              <tns:VoSchedRespReservation>
                                 <tns:ReservationDate>
                                    <xsl:value-of select="ns0:ReservationDate"/>
                                 </tns:ReservationDate>
                                 <tns:ActivityType>
                                    <xsl:value-of select="ns0:ActivityType"/>
                                 </tns:ActivityType>
                                 <tns:ReservationDateLatest>
                                    <xsl:value-of select="ns0:ReservationDateLatest"/>
                                 </tns:ReservationDateLatest>
                                 <tns:BuAddress>
                                    <tns:Sequence>
                                       <xsl:value-of select="ns0:BuAddress/ns0:Sequence"/>
                                    </tns:Sequence>
                                    <tns:BusinessUnit>
                                       <tns:Code>
                                          <xsl:value-of select="ns0:BuAddress/ns0:BusinessUnit/ns0:Code"/>
                                       </tns:Code>
                                       <tns:BuType>
                                          <xsl:value-of select="ns0:BuAddress/ns0:BusinessUnit/ns0:BuType"/>
                                       </tns:BuType>
                                    </tns:BusinessUnit>
                                 </tns:BuAddress>
                              </tns:VoSchedRespReservation>
                           </xsl:for-each>
                        </tns:SchedulingResponseReservationList>
                     </tns:OutVoSchedulingResponse>
                  </tns:DATA>
               </tns:DeliveryScheduleResponse>
            </tns:CreateDeliveryScheduleResponse>
         </tns:DataArea>
      </tns:CreateDeliveryScheduleResponseEBM>
   </xsl:template>
</xsl:stylesheet>
