<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../WSDLs/CreateDeliverySchedule_2.wsdl"/>
      <rootElement name="BsScheduleShipmentResponse" namespace="http://ws.fwk.ikea.com/business-call"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="oramds:/apps/AIAMetaData/IIPComponents/ApplicationConnectorServiceLibrary/DES/V1/ProviderABCS/CreateDeliveryScheduleDESProvABCS.wsdl"/>
      <rootElement name="CreateDeliveryScheduleResponseEBM" namespace="ikea.com/cem/OrderAndDelivery/DeliverySchedule/V0/"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.6.0(build 111214.0600.1553) AT [MON JUN 29 11:58:41 CEST 2015]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:svcdoc="http://xmlns.oracle.com/Services/Documentation/V1"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:corecom="ikea.com/system/iip/IIPHeader/1.0/"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:wsp="http://www.w3.org/ns/ws-policy"
                xmlns:sp="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702"
                xmlns:ns0="ikea.com/system/iip/IIPFaultMessage/1.0/"
                xmlns:ns1="http://schemas.xmlsoap.org/ws/2003/03/addressing"
                xmlns:ns2="http://schemas.oracle.com/service/bpel/common"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:ns4="urn:oasis:names:tc:xacml:2.0:policy:schema:cd:04"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:impl="http://ws.fwk.ikea.com/business-call"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
                xmlns:ns3="urn:oasis:names:tc:xacml:2.0:context:schema:cd:04"
                xmlns:tns="ikea.com/system/iip/CreateDeliveryScheduleDESProvABCSService/1.0/"
                xmlns:curebm="ikea.com/cem/OrderAndDelivery/DeliverySchedule/V0/"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl soap wsdl wsp sp impl xsd wsu svcdoc plnk corecom ns0 ns1 ns2 ns4 ns3 tns curebm xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap">
  <xsl:template match="/">
    <curebm:CreateDeliveryScheduleResponseEBM>
      <curebm:DataArea>
        <curebm:CreateDeliveryScheduleResponse>
          <curebm:DeliveryScheduleResponse>
            <curebm:DATA>
              <curebm:ERRORS>
                <xsl:for-each select="/impl:BsScheduleShipmentResponse/impl:ERRORS/impl:ERROR">
                  <curebm:ERROR>
                    <xsl:attribute name="curebm:EBC">
                      <xsl:value-of select="@EBC"/>
                    </xsl:attribute>
                    <xsl:attribute name="curebm:CODE">
                      <xsl:value-of select="@CODE"/>
                    </xsl:attribute>
                    <xsl:attribute name="curebm:MESSAGE">
                      <xsl:value-of select="@MESSAGE"/>
                    </xsl:attribute>
                    <xsl:for-each select="impl:PARAMETER">
                      <curebm:PARAMETER>
                        <xsl:attribute name="curebm:KEY">
                          <xsl:value-of select="@KEY"/>
                        </xsl:attribute>
                        <xsl:attribute name="curebm:CLASS">
                          <xsl:value-of select="@CLASS"/>
                        </xsl:attribute>
                        <xsl:attribute name="curebm:TYPE">
                          <xsl:value-of select="@TYPE"/>
                        </xsl:attribute>
                        <xsl:value-of select="."/>
                      </curebm:PARAMETER>
                    </xsl:for-each>
                  </curebm:ERROR>
                </xsl:for-each>
              </curebm:ERRORS>
            </curebm:DATA>
          </curebm:DeliveryScheduleResponse>
        </curebm:CreateDeliveryScheduleResponse>
      </curebm:DataArea>
    </curebm:CreateDeliveryScheduleResponseEBM>
  </xsl:template>
</xsl:stylesheet>
