<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="XSD">
      <schema location="oramds:/apps/AIAMetaData/IIPComponents/CommonExchangeModelLibrary/Core/Common/V1/IIPHeader.xsd"/>
      <rootElement name="EBMHeader" namespace="ikea.com/system/iip/IIPHeader/1.0/"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="XSD">
      <schema location="oramds:/apps/AIAMetaData/IIPComponents/CommonExchangeModelLibrary/Core/Common/V1/IIPHeader.xsd"/>
      <rootElement name="EBMHeader" namespace="ikea.com/system/iip/IIPHeader/1.0/"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.6.0(build 111214.0600.1553) AT [FRI OCT 04 12:48:04 CEST 2013]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:wsa="http://schemas.xmlsoap.org/ws/2003/03/addressing"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:xacml="urn:oasis:names:tc:xacml:2.0:policy:schema:cd:04"
                xmlns:corecomcust="ikea.com/system/iip/IIPHeader/1.0/"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:corecomfault="ikea.com/system/iip/IIPFaultMessage/1.0/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:xacml-context="urn:oasis:names:tc:xacml:2.0:context:schema:cd:04"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl wsa xacml corecomcust xsd corecomfault xacml-context bpws xp20 mhdr bpel oraext dvm hwf med ids bpm xdk xref ora socket ldap">
  <xsl:variable name="SenderID" select='"OTM"'/>
  <xsl:variable name="IntegrationScenarioName" select='"CreateDeliverySchedule"'/>
  <xsl:variable name="BusinessScopeIDPath" select='"DeliveryScheduleEBS"'/>
  <xsl:variable name="ServiceName"
                select='"{ikea.com/system/iip/CreateDeliveryScheduleOTMReqABCSService/1.0/}CreateDeliveryScheduleOTMReqABCS"'/>
  <xsl:variable name="CEMName"
                select='"{ikea.com/system/iip/DeliveryScheduleEnterpriseService/1.0/}CreateDeliveryScheduleCEM"'/>
  <xsl:variable name="EBMName"
                select='"{ikea.com/system/iip/DeliveryScheduleEnterpriseService/1.0/}CreateDeliveryScheduleEBM"'/>
  <xsl:variable name="EBSName" select='"{ikea.com/system/iip/DeliveryScheduleEnterpriseService/1.0/}DeliveryScheduleEBS"'/>
  <xsl:variable name="OperationName" select='"CreateDeliverySchedule"'/>
  <xsl:variable name="Verb" select='"CreateDeliverySchedule"'/>
  <xsl:variable name="MessageName" select='"CreateDeliveryScheduleReqMsg"'/>
  <xsl:variable name="MessageID" select="oraext:generate-guid()"/>
  <xsl:template match="/">
    <corecomcust:EBMHeader>
      <corecomcust:MessageID>
        <xsl:value-of select="$MessageID"/>
      </corecomcust:MessageID>
	  <corecomcust:EBMName>
        <xsl:value-of select="$EBMName"/>
      </corecomcust:EBMName>
      <corecomcust:CEMName>
        <xsl:value-of select="$CEMName"/>
      </corecomcust:CEMName>
      <corecomcust:OperationName>
        <xsl:value-of select="$OperationName"/>
      </corecomcust:OperationName>
	  <corecomcust:EnterpriseServiceName>
        <xsl:value-of select="$EBSName"/>
      </corecomcust:EnterpriseServiceName>
      <corecomcust:CreationDateTime>
        <xsl:value-of select="xp20:current-dateTime()"/>
      </corecomcust:CreationDateTime>
      <corecomcust:Sender>
        <corecomcust:ID>
          <xsl:value-of select="$SenderID"/>
        </corecomcust:ID>
      </corecomcust:Sender>
      <corecomcust:EnvironmentID>
        <xsl:text disable-output-escaping="no">PROD</xsl:text>
      </corecomcust:EnvironmentID>
    </corecomcust:EBMHeader>
  </xsl:template>
</xsl:stylesheet>
