<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:tns="ikea.com/iip-splunk/SplunkPersonalInfo/V2/" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:ns0="http://xmlns.oracle.com/apps/otm/transmission/v6.4" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
                xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
                xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:aol="ikea.com/system/iip/CreateDeliveryScheduleOTMReqABCS/1.0/"
                xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
                xmlns:ns1="ikea.com/system/iip/CreateDeliveryScheduleOTMReqABCSService/1.0/"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:ns3="http://xmlns.oracle.com/apps/otm/TransmissionService"
                xmlns:ns2="http://schemas.oracle.com/bpel/extension"
                xmlns:ns4="ikea.com/system/iip/bamAuditMessage/1.0/">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="oramds:/apps/AIAMetaData/IIPComponents/ApplicationObjectLibrary/OTM/V1/wsdls/CreateDeliveryScheduleOTMReqABCS.wsdl"/>
            <oracle-xsl-mapper:rootElement name="Transmission" namespace="http://xmlns.oracle.com/apps/otm/transmission/v6.4"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/CreateDeliveryScheduleOTMReqABCSRef.wsdl"/>
            <oracle-xsl-mapper:rootElement name="SplunkPersonalInfoRequest" namespace="ikea.com/iip-splunk/SplunkPersonalInfo/V2/"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:substitutions>
         <oracle-xsl-mapper:sourceSubst substPath="/ns0:Transmission/ns0:TransmissionBody/ns0:GLogXMLElement/ns0:GLogXMLTransaction"
                                        substElem="ns0:PlannedShipment"/>
      </oracle-xsl-mapper:substitutions>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.4.0(XSLT Build 190828.0353.3300) AT [TUE JUN 13 13:14:23 CEST 2023].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:SplunkPersonalInfoRequest>
       <tns:Technology/>
      <tns:IntegrationName/>
      <tns:ECID/>
      <tns:FlowId/>
      <tns:BankAccountCount/>
      <tns:BankBicCount/>
         <tns:EmailCount>
            <xsl:value-of select="count(/ns0:Transmission/ns0:TransmissionBody/ns0:GLogXMLElement/ns0:PlannedShipment/ns0:Shipment/ns0:ShipmentHeader/ns0:InvolvedParty/ns0:ContactRef/ns0:Contact/ns0:EmailAddress)"/>
         </tns:EmailCount>
         <tns:FaxNumberCount>
            <xsl:value-of select="count(/ns0:Transmission/ns0:TransmissionBody/ns0:GLogXMLElement/ns0:PlannedShipment/ns0:Shipment/ns0:ShipmentHeader/ns0:InvolvedParty/ns0:ContactRef/ns0:Contact/ns0:Fax)"/>
         </tns:FaxNumberCount>
         <tns:NameCount>
            <xsl:value-of select="count(/ns0:Transmission/ns0:TransmissionBody/ns0:GLogXMLElement/ns0:PlannedShipment/ns0:Shipment/ns0:ShipmentHeader/ns0:InvolvedParty/ns0:ContactRef/ns0:Contact/ns0:FirstName)"/>
         </tns:NameCount>
         <tns:PhoneNumberCount>
            <xsl:value-of select="count(/ns0:Transmission/ns0:TransmissionBody/ns0:GLogXMLElement/ns0:PlannedShipment/ns0:Shipment/ns0:ShipmentHeader/ns0:InvolvedParty/ns0:ContactRef/ns0:Contact/ns0:Phone1)"/>
         </tns:PhoneNumberCount>
         <tns:AddressCount/>
      </tns:SplunkPersonalInfoRequest>
   </xsl:template>
</xsl:stylesheet>
