<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" 
                  xmlns:partns="http://xmlns.oracle.com/apps/otm" 
                  xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" 
                  xmlns:ns0="ikea.com/cem/OrderAndDelivery/DeliverySchedule/V0/"
                  xmlns:coreheader="ikea.com/system/iip/IIPHeader/1.0/"
                  xmlns:corefault="ikea.com/system/iip/IIPFaultMessage/1.0/"
                  xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" 
                  xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
                  xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" 
                  xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" 
                  xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" 
                  xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" 
                  xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" 
                  xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" 
                  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
                  xmlns:xsl="http://www.w3.org/1999/XSL/Transform" 
                  xmlns:ns2="ikea.com/system/iip/IIPFaultMessage/1.0/" 
                  exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl partns ns0 ns2 mhdr oraext xp20 xref socket dvm oraxsl">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="oramds:/apps/AIAMetaData/IIPComponents/EnterpriseBusinessServiceLibrary/Core/CEM/DeliverySchedule/V1/DeliveryScheduleEBSV1.wsdl"/>
            <oracle-xsl-mapper:rootElement name="CreateDeliveryScheduleResponseEBM" namespace="ikea.com/cem/OrderAndDelivery/DeliverySchedule/V0/"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="oramds:/apps/AIAMetaData/IIPComponents/ApplicationObjectLibrary/OTM/V1/wsdls/CreateDeliveryScheduleOTMReqABCS.wsdl"/>
            <oracle-xsl-mapper:rootElement name="Transmission" namespace="http://xmlns.oracle.com/apps/otm"/>
            <oracle-xsl-mapper:param name="CreateDeliveryScheduleReqMsg.parameter"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="oramds:/apps/AIAMetaData/IIPComponents/EnterpriseBusinessServiceLibrary/Core/CEM/DeliverySchedule/V1/DeliveryScheduleEBSV1.wsdl"/>
            <oracle-xsl-mapper:rootElement name="IIPFaultMessage" namespace="ikea.com/system/iip/IIPFaultMessage/1.0/"/>
            <oracle-xsl-mapper:param name="IIPAsyncErrorHandlingProcessRequestMessage.FaultMessage"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="oramds:/apps/AIAMetaData/IIPComponents/ApplicationObjectLibrary/OTM/V1/wsdls/CreateDeliveryScheduleOTMReqABCS.wsdl"/>
            <oracle-xsl-mapper:rootElement name="Transmission" namespace="http://xmlns.oracle.com/apps/otm"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.3.0(XSLT Build 170820.1700.2557) AT [WED MAR 25 01:16:00 GMT+05:30 2020].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="CreateDeliveryScheduleReqMsg.parameter"/>
   <xsl:param name="IIPAsyncErrorHandlingProcessRequestMessage.FaultMessage"/>
   <xsl:template match="/">
     <partns:Transmission>
      <partns:TransmissionHeader>
        <partns:Version>
          <xsl:value-of select="$CreateDeliveryScheduleReqMsg.parameter/partns:Transmission/partns:TransmissionHeader/partns:Version"/>
        </partns:Version>
        <partns:TransactionCount>
          <xsl:value-of select="$CreateDeliveryScheduleReqMsg.parameter/partns:Transmission/partns:TransmissionHeader/partns:TransactionCount"/>
        </partns:TransactionCount>
        <partns:SenderHostName>
          <xsl:text disable-output-escaping="no">DES_SCHEDULE_RESPONSE</xsl:text>
        </partns:SenderHostName>
        <partns:ReceiverHostName>
          <xsl:value-of select="$CreateDeliveryScheduleReqMsg.parameter/partns:Transmission/partns:TransmissionHeader/partns:SenderHostName"/>
        </partns:ReceiverHostName>
        <partns:SenderSystemID>
          <xsl:text disable-output-escaping="no">FMW</xsl:text>
        </partns:SenderSystemID>
        <partns:SenderTransmissionNo>
          <xsl:text disable-output-escaping="no"></xsl:text>
        </partns:SenderTransmissionNo>
        <partns:AckSpec>
          <partns:ComMethodGid>
            <partns:Gid>
              <partns:Xid>
                <xsl:value-of select='dvm:lookupValue("oramds:/apps/AIAMetaData/IIPComponents/dvm/Common/Common.dvm","OTM","Communication Method","Value","SERVICE")'/>
              </partns:Xid>
            </partns:Gid>
          </partns:ComMethodGid>
          <partns:AckOption>
            <xsl:text disable-output-escaping="no">NO</xsl:text>
          </partns:AckOption>
          <partns:ContactGid>
            <partns:Gid>
              <partns:DomainName>
                <xsl:text disable-output-escaping="no">I</xsl:text>
              </partns:DomainName>
              <partns:Xid>
                <xsl:text disable-output-escaping="no">DES_SCHEDULE_RESPONSE</xsl:text>
              </partns:Xid>
            </partns:Gid>
          </partns:ContactGid>
        </partns:AckSpec>
        <partns:IsProcessInSequence>
          <xsl:value-of select='dvm:lookupValue("oramds:/apps/AIAMetaData/IIPComponents/dvm/Common/Common.dvm","OTM","Stop Process On Error Yes","Value","Y")'/>
        </partns:IsProcessInSequence>
        <partns:StopProcessOnError>
          <xsl:text disable-output-escaping="no">N</xsl:text>
        </partns:StopProcessOnError>
        <partns:DataQueueGid>
          <partns:Gid>
            <partns:DomainName>I</partns:DomainName>
            <partns:Xid>
              <xsl:value-of select='dvm:lookupValue("oramds:/apps/AIAMetaData/IIPComponents/dvm/Common/Common.dvm","OTM","DataQueuePriority","Value","")'/>
            </partns:Xid>
          </partns:Gid>
        </partns:DataQueueGid>
      </partns:TransmissionHeader>
      <partns:TransmissionBody>
        <partns:GLogXMLElement>
          <partns:ShipmentStatus>
            <partns:ShipmentRefnum>
              <partns:ShipmentRefnumQualifierGid>
                <partns:Gid>
                  <partns:Xid>
                    <xsl:text disable-output-escaping="no">GLOG</xsl:text>
                  </partns:Xid>
                </partns:Gid>
              </partns:ShipmentRefnumQualifierGid>
              <partns:ShipmentRefnumValue>
                <xsl:text disable-output-escaping="no">I.CNS-SHIPMENT</xsl:text>
              </partns:ShipmentRefnumValue>
            </partns:ShipmentRefnum>
            <partns:StatusLevel>
              <xsl:text disable-output-escaping="no">SHIPMENT</xsl:text>
            </partns:StatusLevel>
            <partns:StatusCodeGid>
              <partns:Gid>
                <partns:DomainName>
                  <xsl:text disable-output-escaping="no">I</xsl:text>
                </partns:DomainName>
                <partns:Xid>
                  <xsl:text disable-output-escaping="no">DES</xsl:text>
                </partns:Xid>
              </partns:Gid>
            </partns:StatusCodeGid>
            <xsl:for-each select="$CreateDeliveryScheduleReqMsg.parameter/partns:Transmission/partns:TransmissionBody/partns:GLogXMLElement/partns:PlannedShipment">
              <partns:Remark>
                <partns:RemarkSequence>
                  <xsl:text disable-output-escaping="no">1</xsl:text>
                </partns:RemarkSequence>
                <partns:RemarkQualifierGid>
                  <partns:Gid>
                    <partns:DomainName>
                      <xsl:text disable-output-escaping="no">I</xsl:text>
                    </partns:DomainName>
                    <partns:Xid>
                      <xsl:text disable-output-escaping="no">DES ERROR MESSAGE</xsl:text>
                    </partns:Xid>
                  </partns:Gid>
                </partns:RemarkQualifierGid>
                <partns:RemarkText>
                  <xsl:value-of select='concat(partns:Shipment/partns:ShipmentHeader/partns:ShipmentName,"|","SYSERROR","|")'/>                  
                </partns:RemarkText>
              </partns:Remark>
            </xsl:for-each>
              <partns:Remark>
                <partns:RemarkSequence>
                  <xsl:text disable-output-escaping="no">2</xsl:text>
                </partns:RemarkSequence>
                <partns:RemarkQualifierGid>
                  <partns:Gid>
                    <partns:DomainName>
                      <xsl:text disable-output-escaping="no">I</xsl:text>
                    </partns:DomainName>
                    <partns:Xid>
                      <xsl:text disable-output-escaping="no">DES ERROR MESSAGE</xsl:text>
                    </partns:Xid>
                  </partns:Gid>
                </partns:RemarkQualifierGid>
                <partns:RemarkText>
                  <!--xsl:value-of select="oraext:get-content-as-string(.)"/-->
                  <xsl:value-of select="$IIPAsyncErrorHandlingProcessRequestMessage.FaultMessage/corefault:IIPFaultMessage/corefault:ErrorContext/corefault:ErrorText"/>
                </partns:RemarkText>
              </partns:Remark>
            <partns:FlexFieldStrings>
              <partns:Attribute1>
                <xsl:value-of select="$CreateDeliveryScheduleReqMsg.parameter/partns:Transmission/partns:TransmissionBody/partns:GLogXMLElement/partns:PlannedShipment/partns:Shipment/partns:ShipmentHeader/partns:ShipmentName"/>                
              </partns:Attribute1>
              <partns:Attribute10>
                <xsl:text disable-output-escaping="no">DES</xsl:text>
              </partns:Attribute10>
              <partns:Attribute20>
                <xsl:value-of select='substring-after(substring-after($CreateDeliveryScheduleReqMsg.parameter/partns:Transmission/partns:TransmissionBody/partns:GLogXMLElement/partns:PlannedShipment/partns:Shipment/partns:ShipmentHeader/partns:ShipmentName,"-"),"-")'/>                
              </partns:Attribute20>
            </partns:FlexFieldStrings>
          </partns:ShipmentStatus>
        </partns:GLogXMLElement>
      </partns:TransmissionBody>
    </partns:Transmission>
   </xsl:template>
</xsl:stylesheet>