<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:ns0="ikea.com/cem/OrderAndDelivery/DeliverySchedule/V0/"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ns1="http://xmlns.oracle.com/apps/otm/transmission/v6.4"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
				xmlns:currexebm="ikea.com/cem/OrderAndDelivery/DeliverySchedule/V0/"
                xmlns:tns="http://xmlns.oracle.com/apps/otm/TransmissionService"
                exclude-result-prefixes="xsd oracle-xsl-mapper xsi xsl ns0 ns1 tns mhdr oraext xp20 currexebm xref socket dvm oraxsl"
                xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
                xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:svcdoc="http://xmlns.oracle.com/Services/Documentation/V1"
                xmlns:aol="ikea.com/system/iip/CreateDeliveryScheduleOTMReqABCS/1.0/"
                xmlns:ns5="urn:oasis:names:tc:xacml:2.0:policy:schema:cd:04"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:ebsimpl="ikea.com/system/iip/DeliveryScheduleEnterpriseService/1.0/"
                xmlns:ns2="urn:oasis:names:tc:xacml:2.0:context:schema:cd:04"
                xmlns:ns4="http://schemas.xmlsoap.org/ws/2003/03/addressing"
                xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
                xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns3="http://schemas.oracle.com/service/bpel/common"
                xmlns:corecom="ikea.com/system/iip/IIPHeader/1.0/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
                xmlns:ns7="ikea.com/system/iip/CreateDeliveryScheduleOTMReqABCSService/1.0/"
                xmlns:ns6="ikea.com/system/iip/IIPFaultMessage/1.0/" xmlns:wsp="http://www.w3.org/ns/ws-policy"
                xmlns:wssutil="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="oramds:/apps/AIAMetaData/IIPComponents/EnterpriseBusinessServiceLibrary/Core/CEM/DeliverySchedule/V1/DeliveryScheduleEBSV1.wsdl"/>
        <oracle-xsl-mapper:rootElement name="CreateDeliveryScheduleResponseEBM"
                                       namespace="ikea.com/cem/OrderAndDelivery/DeliverySchedule/V0/"/>
      </oracle-xsl-mapper:source>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="oramds:/apps/AIAMetaData/IIPComponents/ApplicationObjectLibrary/OTM/V1/wsdls/CreateDeliveryScheduleOTMReqABCS.wsdl"/>
        <oracle-xsl-mapper:rootElement name="Transmission"
                                       namespace="http://xmlns.oracle.com/apps/otm/transmission/v6.4"/>
        <oracle-xsl-mapper:param name="CreateDeliveryScheduleReqMsg.parameter"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="oramds:/apps/AIAMetaData/IIPComponents/ApplicationObjectLibrary/OTM/V3/wsdls/Transmission.wsdl"/>
        <oracle-xsl-mapper:rootElement name="publish" namespace="http://xmlns.oracle.com/apps/otm/TransmissionService"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.4.0(XSLT Build 190828.0353.3300) AT [THU JUN 29 17:03:16 CEST 2023].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:param name="CreateDeliveryScheduleReqMsg.parameter"/>
  <xsl:template match="/">
    <tns:publish>
      <ns1:Transmission>
        <ns1:TransmissionHeader>
          <ns1:Version>
            <xsl:value-of select="$CreateDeliveryScheduleReqMsg.parameter/ns1:Transmission/ns1:TransmissionHeader/ns1:Version"/>
          </ns1:Version>
          <ns1:TransactionCount>
            <xsl:value-of select="$CreateDeliveryScheduleReqMsg.parameter/ns1:Transmission/ns1:TransmissionHeader/ns1:TransactionCount"/>
          </ns1:TransactionCount>
          <ns1:SenderHostName>
            <xsl:text disable-output-escaping="no">DES_SCHEDULE_RESPONSE</xsl:text>
          </ns1:SenderHostName>
          <ns1:ReceiverHostName>
            <xsl:value-of select="$CreateDeliveryScheduleReqMsg.parameter/ns1:Transmission/ns1:TransmissionHeader/ns1:SenderHostName"/>
          </ns1:ReceiverHostName>
          <ns1:SenderSystemID>
            <xsl:text disable-output-escaping="no">FMW</xsl:text>
          </ns1:SenderSystemID>
          <ns1:SenderTransmissionNo>
            <xsl:text disable-output-escaping="no"></xsl:text>
          </ns1:SenderTransmissionNo>
          <ns1:AckSpec>
            <ns1:ComMethodGid>
              <ns1:Gid>
                <ns1:Xid>
                  <xsl:value-of select='dvm:lookupValue("oramds:/apps/AIAMetaData/IIPComponents/dvm/Common/Common.dvm","OTM","Communication Method","Value","SERVICE")'/>
                </ns1:Xid>
              </ns1:Gid>
            </ns1:ComMethodGid>
            <ns1:AckOption>
              <xsl:text disable-output-escaping="no">NO</xsl:text>
            </ns1:AckOption>
            <ns1:ContactGid>
              <ns1:Gid>
                <ns1:DomainName>
                  <xsl:text disable-output-escaping="no">I</xsl:text>
                </ns1:DomainName>
                <ns1:Xid>
                  <xsl:text disable-output-escaping="no">DES_SCHEDULE_RESPONSE</xsl:text>
                </ns1:Xid>
              </ns1:Gid>
            </ns1:ContactGid>
          </ns1:AckSpec>
          <ns1:IsProcessInSequence>
            <xsl:value-of select='dvm:lookupValue("oramds:/apps/AIAMetaData/IIPComponents/dvm/Common/Common.dvm","OTM","Stop Process On Error Yes","Value","Y")'/>
          </ns1:IsProcessInSequence>
          <ns1:StopProcessOnError>
            <xsl:text disable-output-escaping="no">N</xsl:text>
          </ns1:StopProcessOnError>
          <ns1:DataQueueGid>
            <ns1:Gid>
              <ns1:DomainName>I</ns1:DomainName>
              <ns1:Xid>
                <xsl:value-of select='dvm:lookupValue("oramds:/apps/AIAMetaData/IIPComponents/dvm/Common/Common.dvm","OTM","DataQueuePriority","Value","")'/>
              </ns1:Xid>
            </ns1:Gid>
          </ns1:DataQueueGid>
        </ns1:TransmissionHeader>
        <ns1:TransmissionBody>
          <ns1:GLogXMLElement>
            <ns1:ShipmentStatus>
              <ns1:ShipmentRefnum>
                <ns1:ShipmentRefnumQualifierGid>
                  <ns1:Gid>
                    <ns1:Xid>
                      <xsl:text disable-output-escaping="no">GLOG</xsl:text>
                    </ns1:Xid>
                  </ns1:Gid>
                </ns1:ShipmentRefnumQualifierGid>
                <ns1:ShipmentRefnumValue>
                  <xsl:text disable-output-escaping="no">I.CNS-SHIPMENT</xsl:text>
                </ns1:ShipmentRefnumValue>
              </ns1:ShipmentRefnum>
              <ns1:StatusLevel>
                <xsl:text disable-output-escaping="no">SHIPMENT</xsl:text>
              </ns1:StatusLevel>
              <ns1:StatusCodeGid>
                <ns1:Gid>
                  <ns1:DomainName>
                    <xsl:text disable-output-escaping="no">I</xsl:text>
                  </ns1:DomainName>
                  <ns1:Xid>
                    <xsl:text disable-output-escaping="no">DES</xsl:text>
                  </ns1:Xid>
                </ns1:Gid>
              </ns1:StatusCodeGid>
              <xsl:for-each select="$CreateDeliveryScheduleReqMsg.parameter/ns1:Transmission/ns1:TransmissionBody/ns1:GLogXMLElement/ns1:PlannedShipment">
                <ns1:Remark>
                  <ns1:RemarkSequence>
                    <xsl:text disable-output-escaping="no">1</xsl:text>
                  </ns1:RemarkSequence>
                  <ns1:RemarkQualifierGid>
                    <ns1:Gid>
                      <ns1:DomainName>
                        <xsl:text disable-output-escaping="no">I</xsl:text>
                      </ns1:DomainName>
                      <ns1:Xid>
                        <xsl:text disable-output-escaping="no">DES ERROR MESSAGE</xsl:text>
                      </ns1:Xid>
                    </ns1:Gid>
                  </ns1:RemarkQualifierGid>
                  <ns1:RemarkText>
                    <xsl:value-of select='concat(ns1:Shipment/ns1:ShipmentHeader/ns1:ShipmentName,"|","SYSERROR","|")'/>
                  </ns1:RemarkText>
                </ns1:Remark>
              </xsl:for-each>
              <xsl:for-each select="/currexebm:CreateDeliveryScheduleResponseEBM/currexebm:DataArea/currexebm:CreateDeliveryScheduleResponse/currexebm:DeliveryScheduleResponse/currexebm:DATA/currexebm:ERRORS/currexebm:ERROR">
                <ns1:Remark>
                  <ns1:RemarkSequence>
                    <xsl:text disable-output-escaping="no">2</xsl:text>
                  </ns1:RemarkSequence>
                  <ns1:RemarkQualifierGid>
                    <ns1:Gid>
                      <ns1:DomainName>
                        <xsl:text disable-output-escaping="no">I</xsl:text>
                      </ns1:DomainName>
                      <ns1:Xid>
                        <xsl:text disable-output-escaping="no">DES ERROR MESSAGE</xsl:text>
                      </ns1:Xid>
                    </ns1:Gid>
                  </ns1:RemarkQualifierGid>
                  <ns1:RemarkText>
                    <!--xsl:value-of select="oraext:get-content-as-string(.)"/-->
                    <xsl:value-of select="$ErrorText_OutputVariable"/>
                  </ns1:RemarkText>
                </ns1:Remark>
              </xsl:for-each>
              <ns1:FlexFieldStrings>
                <ns1:Attribute1>
                  <xsl:value-of select="$CreateDeliveryScheduleReqMsg.parameter/ns1:Transmission/ns1:TransmissionBody/ns1:GLogXMLElement/ns1:PlannedShipment/ns1:Shipment/ns1:ShipmentHeader/ns1:ShipmentName"/>
                </ns1:Attribute1>
                <ns1:Attribute10>
                  <xsl:text disable-output-escaping="no">DES</xsl:text>
                </ns1:Attribute10>
                <ns1:Attribute20>
                  <xsl:value-of select='substring-after(substring-after($CreateDeliveryScheduleReqMsg.parameter/ns1:Transmission/ns1:TransmissionBody/ns1:GLogXMLElement/ns1:PlannedShipment/ns1:Shipment/ns1:ShipmentHeader/ns1:ShipmentName,"-"),"-")'/>
                </ns1:Attribute20>
              </ns1:FlexFieldStrings>
            </ns1:ShipmentStatus>
          </ns1:GLogXMLElement>
        </ns1:TransmissionBody>
      </ns1:Transmission>
    </tns:publish>
  </xsl:template>
</xsl:stylesheet>
