<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="CreateDeliveryScheduleOTMReqABCS"
     targetNamespace="ikea.com/system/iip/CreateDeliveryScheduleOTMReqABCSService/1.0/"
     xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:xs="http://www.w3.org/2001/XMLSchema"
     xmlns:client="ikea.com/system/iip/CreateDeliveryScheduleOTMReqABCSService/1.0/"
     xmlns:ns1="http://schemas.oracle.com/bpel/extension"
     xmlns:ns2="http://xmlns.oracle.com/apps/otm/TransmissionService"
     xmlns:ns3="ikea.com/iip-splunk/SplunkPersonalInfo/V2/"
     xmlns:ns4="http://www.example.org"
    >
    <plnk:partnerLinkType name="CreateDeliveryScheduleOTMReqABCS">
        <plnk:role name="CreateDeliveryScheduleOTMReqABCSProvider">
            <plnk:portType name="client:CreateDeliveryScheduleOTMReqABCS"/>
        </plnk:role>
    </plnk:partnerLinkType>
    <wsdl:import namespace="ikea.com/system/iip/CreateDeliveryScheduleOTMReqABCSService/1.0/" location="oramds:/apps/AIAMetaData/IIPComponents/ApplicationObjectLibrary/OTM/V1/wsdls/CreateDeliveryScheduleOTMReqABCS.wsdl"/>
    <wsdl:import namespace="http://xmlns.oracle.com/apps/otm/TransmissionService" location="oramds:/apps/AIAMetaData/IIPComponents/ApplicationObjectLibrary/OTM/V3/wsdls/Transmission.wsdl"/>
    <wsdl:types>
        <xs:schema>
            <xs:import namespace="ikea.com/system/iip/bamAuditMessage/1.0/" schemaLocation="oramds:/apps/AIAMetaData/IIPComponents/InfrastructureServiceLibrary/V1/schemas/BAMMetrics_V2.xsd"/>
        </xs:schema>
        <xs:schema>
            <import namespace="ikea.com/iip-splunk/SplunkPersonalInfo/V2/" schemaLocation="oramds:/apps/AIAMetaData/IIPComponents/CommonExchangeModelLibrary/Core/iip-splunk/V2/SplunkPersonalInfo.xsd"/>
        </xs:schema>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="ikea.com/iip-splunk/SplunkPersonalInfo/V2/" schemaLocation="oramds:/apps/AIAMetaData/IIPComponents/CommonExchangeModelLibrary/Core/iip-splunk/V2/SplunkPersonalInfo.xsd"/>
        </xsd:schema>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://www.example.org" schemaLocation="../Schemas/SubsitutionElement.xsd"/>
        </xsd:schema>
    </wsdl:types>
</wsdl:definitions>
