<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     targetNamespace="ikea.com/system/iip/DeliveryScheduleEnterpriseService/1.0/"
     xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:tns="ikea.com/system/iip/DeliveryScheduleEnterpriseService/1.0/"
     xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    >
    <plnk:partnerLinkType name="DeliveryScheduleEBSResponse_PL">
        <plnk:role name="DeliveryScheduleEBSResponse_Role">
            <plnk:portType name="tns:DeliveryScheduleEBS"/>
        </plnk:role>
    </plnk:partnerLinkType>
    <wsdl:import namespace="ikea.com/system/iip/DeliveryScheduleEnterpriseService/1.0/" 
                 location="oramds:/apps/AIAMetaData/IIPComponents/EnterpriseBusinessServiceLibrary/Core/CEM/DeliverySchedule/V1/DeliveryScheduleEBSV1.wsdl"/>
</wsdl:definitions>
