<?xml version='1.0' encoding='utf-8'?>
<wsdl:definitions xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xs="http://www.w3.org/2001/XMLSchema" name="CreateDeliveryScheduleDESProvABCS" targetNamespace="ikea.com/system/iip/CreateDeliveryScheduleDESProvABCSService/1.0/" xmlns:client="ikea.com/system/iip/CreateDeliveryScheduleDESProvABCSService/1.0/" xmlns:ns1="http://schemas.oracle.com/bpel/extension">



    <plnk:partnerLinkType name="CreateDeliveryScheduleDESProvABCS">
        <plnk:role name="CreateDeliveryScheduleDESProvABCSProvider">
            <plnk:portType name="client:CreateDeliveryScheduleDESProvABCS" />
        </plnk:role>
    </plnk:partnerLinkType>

    <wsdl:import location="oramds:/apps/AIAMetaData/IIPComponents/ApplicationConnectorServiceLibrary/DES/V1/ProviderABCS/CreateDeliveryScheduleDESProvABCS.wsdl" namespace="ikea.com/system/iip/CreateDeliveryScheduleDESProvABCSService/1.0/" />
<wsdl:types>
						<xs:schema>
							<xs:import namespace="ikea.com/system/iip/bamAuditMessage/1.0/" schemaLocation="oramds:/apps/AIAMetaData/IIPComponents/InfrastructureServiceLibrary/V1/schemas/BAMMetrics_V2.xsd" />
						</xs:schema>
					</wsdl:types></wsdl:definitions>