<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
    
     targetNamespace="ikea.com/system/iip/IIPAsyncErrorHandlingService/1.0/"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
     xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:ns1="ikea.com/system/iip/IIPAsyncErrorHandlingService/1.0/"
     xmlns:ns2="http://schemas.xmlsoap.org/ws/2003/03/addressing"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <wsdl:import namespace="ikea.com/system/iip/IIPAsyncErrorHandlingService/1.0/" location="oramds:/apps/AIAMetaData/IIPComponents/InfrastructureServiceLibrary/V1/wsdls/IIPAsyncErrorHandlingProcess.wsdl"/>
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://schemas.xmlsoap.org/ws/2003/03/addressing" schemaLocation="../Schemas/ws-addressing.xsd"/>
        </xsd:schema>
    </wsdl:types>
</wsdl:definitions>
